name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch submodules
      run: | 
          git submodule init 
          git submodule update
      
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B stardust_build
      
    - name: Build
      # Build your program with the given configuration
      run: |
        cd stardust_build
        make
        ls -l
    - name: Upload build artifact
      uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: stardust_build
        
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: stardust_build

      - name: Valgrind
        run: |
          cd stardust_build
          ls -l
          sudo apt install -y --no-install-recommends valgrind 
          valgrind --error-exitcode=1 --leak-check=full --trace-children=yes -s ./stardust init test_project
          valgrind --error-exitcode=1 --leak-check=full --trace-children=yes -s ./stardust add-breakthrough test_breakthrough
          valgrind --error-exitcode=1 --leak-check=full --trace-children=yes -s echo "test_artifact" | ./stardust create-artifact .
